name: fluttermoji
description: A light-weight and highly customizable SVG avatar library for Flutter apps. Provides a Customizer Widget, CircleAvatar and other utility functions that are ready-to-use.
version: 1.0.0
# author: Suraj Kumar
homepage: https://github.com/psk907/fluttermoji

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - attributeicons/
